### ISSUE TITLE
powerjoular usage in vms or aws ec2 instances

### ISSUE THREAD

**Issue by akather** [joular/powerjoular#25]
Hi,
I am not getting output from powerjoular for my ec2 instance. its running on ubuntu.

ubuntu@ip-172-31-40-7:~/powerjoular/installer$ sudo powerjoular
System info:
        Platform: intel
Total Power: 0.00 Watts (CPU: 0.00 W)   /\ 0.00 Watts^C
--------------------------
Total energy: 0.00 Joules, including:
        CPU energy: 0.00 Joules
        GPU energy: 0.00 Joules
--------------------------

I tried attaching pid to powerjoular command, and make powerjoular running for quite some time.
But, still same output. Values are always coming as zero.

There are no files inside, /sys/class/power* folders.
ubuntu@ip-172-31-40-7:/sys/class/power_supply$ ls -lrt
total 0
ubuntu@ip-172-31-40-7:/sys/class/power_supply$ cd -
/sys/class/powercap
ubuntu@ip-172-31-40-7:/sys/class/powercap$ ls -lrt
total 0

Any suggestions?

Thanks,
AK

**Comment by adelnoureddine** [comment]
Dear @akather, PowerJoular on Linux servers and PCs uses the RAPL interface in the Linux kernel, accessed through powercap.
Unfortunately, powercap data are not available from within virtual machines (such as EC2).

Unless virtual machines provide access to the host's RAPL interface, it is impossible to get any energy measurements of the CPU.
Some other tools, such as PowerAPI or Scaphandre, install an additional module on the bare metal host that read RAPL and send it through the VM.
However, this requires having access to the host machine (which isn't usually the case in most virtual machines cloud offering, including Amazon).
Such workaround is in our todo list but not high in priority due to the very limited number of providers allowing bare metal access.
